### ISSUE TITLE
Accumbens area in aseg

### ISSUE THREAD

**Issue by PbPostDoc** [LCBC-UiO/ggsegExtra#16]
Hi! I apologize if I'm missing something very obvious, but it seems like there is an "accumbens area" demarcation in aseg_3d but not aseg. Is this correct? Or, am I missing something obvious?

**Comment by Athanasiamo** [comment]
Hi!

No, you are quite right. We found it impossible to create images of the subcortical structures in 2D that actually managed to depict all the segmentations. This is really a caveat when trying to make something 3-dimensional into 2 dimensions. The cortical atlases are easier to project into 2D due to cortical inflation procedures, but the subcortical structures have no such possibility. 

I'd recommend switching to ggse3d for areas not visible in 2d.

**Comment by PbPostDoc** [comment]
Thank you for the clarification!
