### ISSUE TITLE
hoCort - stacking

### ISSUE THREAD

**Issue by richardbeare** [LCBC-UiO/ggsegExtra#2]
What do I need to do to enable stacking with the new Harvard-Oxford atlas?

**Comment by Athanasiamo** [comment]
It should already be working. If you are experiencing the hemispheres stacking too close to eachother, you can update the main ggseg package, I did a very minor edit to the stacking function yesterday so that the extra space is added. 

```ggseg(atlas=hoCort, position = "stacked")```
![image](https://user-images.githubusercontent.com/14014329/55774569-f0515600-5a95-11e9-9432-8a4c7915ca69.png)

**Comment by Athanasiamo** [comment]
oh wait! Those labels arent right! :D

**Comment by richardbeare** [comment]
Oh, I used "stack" instead of stacked. Silly me

**Comment by Athanasiamo** [comment]
oh good! I'll have a fix for those labels very soon :)
